name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama que estés usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up GitHub Pages
        run: |
          echo "Deploying to GitHub Pages..."
          mkdir -p public
          cp -r * public/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
